// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKaO6LckS-oG_V2D4zlEaYswIomvq5Ukk',
    appId: '1:141972551010:web:b2141207ecd98c58b6e83b',
    messagingSenderId: '141972551010',
    projectId: 'eventmanagementapp-1a995',
    authDomain: 'eventmanagementapp-1a995.firebaseapp.com',
    storageBucket: 'eventmanagementapp-1a995.firebasestorage.app',
    measurementId: 'G-HFER2LSKNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDfJ54i7zu6DVJ5RdRdfeJHBb1YXtXtY',
    appId: '1:141972551010:android:da361f2a216be4b0b6e83b',
    messagingSenderId: '141972551010',
    projectId: 'eventmanagementapp-1a995',
    storageBucket: 'eventmanagementapp-1a995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp2pvp4wT-Dti70V8vU0-bDtqQWbhO0Gw',
    appId: '1:141972551010:ios:cfc346ede4f446ceb6e83b',
    messagingSenderId: '141972551010',
    projectId: 'eventmanagementapp-1a995',
    storageBucket: 'eventmanagementapp-1a995.firebasestorage.app',
    iosClientId: '141972551010-adiu420ibh6747dsjsl60hsohorm4ftq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp2pvp4wT-Dti70V8vU0-bDtqQWbhO0Gw',
    appId: '1:141972551010:ios:cfc346ede4f446ceb6e83b',
    messagingSenderId: '141972551010',
    projectId: 'eventmanagementapp-1a995',
    storageBucket: 'eventmanagementapp-1a995.firebasestorage.app',
    iosClientId: '141972551010-adiu420ibh6747dsjsl60hsohorm4ftq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKaO6LckS-oG_V2D4zlEaYswIomvq5Ukk',
    appId: '1:141972551010:web:a736674b7871ed3eb6e83b',
    messagingSenderId: '141972551010',
    projectId: 'eventmanagementapp-1a995',
    authDomain: 'eventmanagementapp-1a995.firebaseapp.com',
    storageBucket: 'eventmanagementapp-1a995.firebasestorage.app',
    measurementId: 'G-84KS942Q5P',
  );

}